### ISSUE TITLE
Set lang attribute to index.html

### ISSUE THREAD

**Issue by siwalikm** [siwalikm/Flash#4]
## Checklist (won't be merged if they are not all ticked)
- [ ] <html> element does not have a [lang] attribute, set it as `en`.
- [ ] I didn't modify any test case 🔴
- [ ] I've ⭐️ the repository (or not, all up to you)
- [ ] And more importantly, I've had fun! 🍺
 
More about lang tag: [url](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang)

**Comment by pauliax** [comment]
Working on this :)
